# Uncomment the next line to define a global platform for your project
 platform :ios, '17.2'

target 'PerfectRep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerfectRep
  pod 'SnapKit', '~> 5.0.0'
  pod 'Charts'
  pod 'CoreStore', '~> 6.3.1'
  pod 'CoreGPX'
  pod 'Cache'

end
