# Uncomment the next line to define a global platform for your project
 platform :ios, '17.2'

target 'PerfectRep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerfectRep
  pod 'SnapKit'
  pod 'DGCharts'
  pod 'CoreStore', '~> 9.2.0' 
  pod 'CoreGPX'
  pod 'Cache'

end
